# Ranking

Consider the network of 6 webpages shown below.
![title](imgs/ranking_network.jpg)

The arrows in this picture show the direction of the links between the pages. For example, Page 1 links to Pages 2 and 5 because there are arrows from Page 1 to both Page 2 and Page 5. We are going to implement the (full) PageRank algorithm for this network.

1) Construct the transition matrix $P$ for a user that simply keeps clicking successive links at random in this network (i.e., the random surfer model).

In [1]:
import numpy as np

P = np.array([[0, 0.5, 0, 0, 0.5, 0],
              [0.5, 0, 0.5, 0, 0, 0],
              [0, 0.25, 0, 0.25, 0.25, 0.25],
              [0, 1/3, 1/3, 0, 0, 1/3],
              [0, 0, 0, 0, 0, 0],
              [0, 0, 0.5, 0, 0.5, 0]
])

2) Construct the transition matrix $S$ for a user that will also jump to random pages if there are no further links

In [5]:
S = np.zeros_like(P)

N = [2, 2, 4, 3, 0, 2]

row, col = P.shape

for i in range(row):
    for j in range(col):
        if N[i] == 0:
            S[i][j] = P[i][j] + 1/6
        elif N[i] > 0:
            S[i][j] = P[i][j]

print(S)


[[0.         0.5        0.         0.         0.5        0.        ]
 [0.5        0.         0.5        0.         0.         0.        ]
 [0.         0.25       0.         0.25       0.25       0.25      ]
 [0.         0.33333333 0.33333333 0.         0.         0.33333333]
 [0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]
 [0.         0.         0.5        0.         0.5        0.        ]]


3) Construct the Google matrix $G$ for a user that will also periodically get bored with probability $1-\alpha = 0.15$ so $\alpha = 0.85$.

In [6]:
alpha = 0.85
G = alpha * S + (1-alpha)/6

print(G)

[[0.025      0.45       0.025      0.025      0.45       0.025     ]
 [0.45       0.025      0.45       0.025      0.025      0.025     ]
 [0.025      0.2375     0.025      0.2375     0.2375     0.2375    ]
 [0.025      0.30833333 0.30833333 0.025      0.025      0.30833333]
 [0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]
 [0.025      0.025      0.45       0.025      0.45       0.025     ]]


4) Use the power method starting from $\pi_0 = \begin{bmatrix} 1/6 \\ 1/6 \\ 1/6 \\ 1/6 \\ 1/6\\ 1/6 \end{bmatrix}$ to compute an approximation of $\pi_\infty$. Stop when $||\pi_k - \pi_{k-1}||_2 < 1 \times 10^{-8}$.

In [18]:
def power(pi_kminus1):
    pi_k = G.T @ pi_kminus1
    return pi_k

# Code here
# initializing variables
pi_kminus1 = np.array([
                [1/6], [1/6], [1/6], [1/6], [1/6], [1/6]])
# pi_kminus1 = pi_kminus1.T
# print(pi_kminus1)
pi_k = power(pi_kminus1)



while np.linalg.norm(pi_k - pi_kminus1) > 1e-8:
    pi_kminus1 = pi_k
    pi_k = power(pi_kminus1)


print(pi_k)

[[0.13648411]
 [0.18999778]
 [0.22172183]
 [0.10285094]
 [0.2169533 ]
 [0.13199204]]


5) Print the ranking of the pages from most important to least important.

In [19]:
print(pi_k.min())

0.10285093872104113
