In [2]:
import numpy as np


one_n = np.array([[0.25, 0.25, 0.25, 0.25],
                  [0.25, 0.25, 0.25, 0.25],
                  [0.25, 0.25, 0.25, 0.25],
                  [0.25, 0.25, 0.25, 0.25]
])

k = np.array([
                [1, 0, 1, 0],
                [0, 1, 0, 1],
                [1, 0, 1, 0],
                [0, 1, 0, 1]
])

In [3]:
k_telta = k - one_n@k - k@one_n + one_n@k@one_n

print(k_telta)

[[ 0.5 -0.5  0.5 -0.5]
 [-0.5  0.5 -0.5  0.5]
 [ 0.5 -0.5  0.5 -0.5]
 [-0.5  0.5 -0.5  0.5]]


### Q3

In [6]:
H = np.array([  [0.75, -0.25, -0.25, -0.25],
                [-0.25, 0.75, -0.25, -0.25],
                [-0.25, -0.25, 0.75, -0.25],
                [-0.25, -0.25, -0.25, 0.75]
])

D = np.array([
            [0, 2, 4, 2],
            [2, 0, 2, 4],
            [4, 2, 0, 2],
            [2, 4, 2, 0]
])

X = np.array([
    [1, 0],
    [0, 1],
    [-1, 0],
    [0, -1]
])

b = X@X.T
print(b)

B = -1/2 * H @ D @ H

print(B)

[[ 1  0 -1  0]
 [ 0  1  0 -1]
 [-1  0  1  0]
 [ 0 -1  0  1]]
[[ 1.  0. -1.  0.]
 [ 0.  1.  0. -1.]
 [-1.  0.  1.  0.]
 [ 0. -1.  0.  1.]]


In [7]:
from numpy import linalg as LA

w, v = LA.eig(B)

print(w)

print(v)

[2. 0. 2. 0.]
[[ 0.70710678  0.70710678  0.          0.        ]
 [ 0.          0.          0.70710678  0.70710678]
 [-0.70710678  0.70710678  0.          0.        ]
 [ 0.          0.         -0.70710678  0.70710678]]
